# for Linux
COMPILER       = ifort
#COMPILERFLAGS  =   -g -CB  -align all -w -autodouble -static -fpp -traceback
COMPILERFLAGS  =   -O3 -xW -align all -no-prec-div -w -autodouble -static -fpp 
#COMPILERFLAGS  =   -O3 -xW -qp -traceback -no-prec-div -w -autodouble -static -fpp 
#COMPILERFLAGS  =   -O3 -CB -traceback -no-prec-div -w -autodouble -static -fpp 
#COMPILERFLAGS  =   -O1  -autodouble -static
#COMPILERFLAGS  =   -O3 -xW  -w -autodouble -static -fpp -pg
#COMPILERFLAGS = -O2 -w -autodouble -static -xW -save
#COMPILERFLAGS  =   -O2 -w -autodouble -ipo -fpp -static
#COMPILERFLAGS2  =  -O3 -xW -traceback -ip  -w -autodouble  -fpp -static
#COMPILERFLAGS2  =  -O3 -xW -traceback -ip -align all -w -autodouble  -fpp -static
COMPILERFLAGS2  =  -O3 -xW -ip -qp -w -autodouble  -fpp -static
#COMPILERFLAGS2  =  -g -CB  -w -autodouble  -fpp -static -traceback
#COMPILERFLAGS2  =  -O1  -w -autodouble  -fpp -static
#COMPILERFLAGS3  =  -g -xW  -w -autodouble  -fpp -static
COMPILERFLAGS3  =  -g -w -autodouble -align all -fpp -static
LINKER         = $(COMPILER)
LINKERFLAGS    = $(COMPILERFLAGS)




SOURCE_TRAILER = .F90
EXEC           = essai
OBJSPERS	   = main.o restart.o fft.o falr.o init.o  generlcgo.o\
                     static.o dynamic.o lda.o util.o abso_bc.o\
                     pseudosoft.o pseudogoed.o ionmd.o forces.o findiff.o\
                     carlo.o localize.o subgrids.o analyse.o\
                     sic.o sicc.o rho.o rhoc.o nonloc.o nonlocc.o\
                     schmid.o zeroforce.o coulex.o functions.o\
                     localize_rad.o symmcond_step.o loc_mfield.o givens.o\
                     parallele.o expevol.o 2stUT.o 2stUTc.o\
                     pot_substrate.o forces_substrate.o md_substrate.o\
                     short.o image.o lattice.o
OBJS		   = $(OBJSPERS) $(OBJSGEN) 
SHELL = /bin/sh

#---------------------------------------------------------	
all:$(EXEC) 
$(EXEC):$(OBJS) 	
	$(LINKER) $(LINKERFLAGS) -o $@  $(OBJS) $(STDLIB)
	mv $(EXEC) ../.
#
$(OBJSPERS) : define.h all.inc Makefile init.inc falr.inc com.inc work3D.inc
.SUFFIXES:  .o .F90

.f90.o:                                                     
	$(COMPILER) $(COMPILERFLAGS) -c $<    

.F90.o:                                                     
	$(COMPILER) $(COMPILERFLAGS) $(PREFLAGS) -c $<    

fft.o: fft.F90 define.h com.inc Makefile
	$(COMPILER) $(COMPILERFLAGS2) -c -o fft.o fft.F90

localize_rad.o: localize_rad.F90 define.h com.inc Makefile
     

sic.o: sicnew.F90 define.h com.inc Makefile
	$(COMPILER) $(COMPILERFLAGS) -DREALSWITCH  -c -o sic.o sicnew.F90
	$(COMPILER) $(COMPILERFLAGS) -DCOMPLEXSWITCH  -c -o sicc.o sicnew.F90

rho.o: rho.F90 define.h com.inc Makefile
	$(COMPILER) $(COMPILERFLAGS) -DREALSWITCH  -c rho.F90
	$(COMPILER) $(COMPILERFLAGS) -DCOMPLEXSWITCH  -c -o rhoc.o rho.F90

nonloc.o: nonloc.F90 define.h com.inc Makefile
	$(COMPILER) $(COMPILERFLAGS) -DREALSWITCH  -c nonloc.F90
	$(COMPILER) $(COMPILERFLAGS) -DCOMPLEXSWITCH  -c -o nonlocc.o nonloc.F90

2stUT.o: 2stUT.F90 define.h com.inc Makefile
	$(COMPILER) $(COMPILERFLAGS) -DREALSWITCH  -c 2stUT.F90
	$(COMPILER) $(COMPILERFLAGS) -DCOMPLEXSWITCH  -c -o 2stUTc.o 2stUT.F90


givens.o: givens.F90 Makefile
	$(COMPILER) $(COMPILERFLAGS3) -c -o givens.o givens.F90

init.o: init.F90 Makefile
	$(COMPILER) $(COMPILERFLAGS3) -c -o init.o init.F90



